const flagByTeamName: Record<string, string> = {
  Algeria: "https://flagcdn.com/dz.svg",
  Argentina: "https://flagcdn.com/ar.svg",
  Australia: "https://flagcdn.com/au.svg",
  Austria: "https://flagcdn.com/at.svg",
  Belgium: "https://flagcdn.com/be.svg",
  "Bosnia and Herzegovina": "https://flagcdn.com/ba.svg",
  Brazil: "https://flagcdn.com/br.svg",
  "Cabo Verde": "https://flagcdn.com/cv.svg",
  Canada: "https://flagcdn.com/ca.svg",
  Colombia: "https://flagcdn.com/co.svg",
  "Congo DR": "https://flagcdn.com/cd.svg",
  "Cote d'Ivoire": "https://flagcdn.com/ci.svg",
  Croatia: "https://flagcdn.com/hr.svg",
  Curacao: "https://flagcdn.com/cw.svg",
  Czechia: "https://flagcdn.com/cz.svg",
  Ecuador: "https://flagcdn.com/ec.svg",
  Egypt: "https://flagcdn.com/eg.svg",
  England: "https://flagcdn.com/gb-eng.svg",
  France: "https://flagcdn.com/fr.svg",
  Germany: "https://flagcdn.com/de.svg",
  Ghana: "https://flagcdn.com/gh.svg",
  Haiti: "https://flagcdn.com/ht.svg",
  "IR Iran": "https://flagcdn.com/ir.svg",
  Iraq: "https://flagcdn.com/iq.svg",
  Japan: "https://flagcdn.com/jp.svg",
  Jordan: "https://flagcdn.com/jo.svg",
  "Korea Republic": "https://flagcdn.com/kr.svg",
  Mexico: "https://flagcdn.com/mx.svg",
  Morocco: "https://flagcdn.com/ma.svg",
  Netherlands: "https://flagcdn.com/nl.svg",
  "New Zealand": "https://flagcdn.com/nz.svg",
  Norway: "https://flagcdn.com/no.svg",
  Panama: "https://flagcdn.com/pa.svg",
  Paraguay: "https://flagcdn.com/py.svg",
  Portugal: "https://flagcdn.com/pt.svg",
  Qatar: "https://flagcdn.com/qa.svg",
  "Saudi Arabia": "https://flagcdn.com/sa.svg",
  Scotland: "https://flagcdn.com/gb-sct.svg",
  Senegal: "https://flagcdn.com/sn.svg",
  "South Africa": "https://flagcdn.com/za.svg",
  Spain: "https://flagcdn.com/es.svg",
  Sweden: "https://flagcdn.com/se.svg",
  Switzerland: "https://flagcdn.com/ch.svg",
  Tunisia: "https://flagcdn.com/tn.svg",
  Turkiye: "https://flagcdn.com/tr.svg",
  "United States": "https://flagcdn.com/us.svg",
  Uruguay: "https://flagcdn.com/uy.svg",
  Uzbekistan: "https://flagcdn.com/uz.svg",
};

export function getTeamFlagUrl(teamName: string) {
  return flagByTeamName[teamName] ?? null;
}
