create index idx_profiles_role on public.profiles(role);
create index idx_profiles_participant_id on public.profiles(participant_id);
create index idx_participants_active on public.participants(active);
create index idx_participants_name on public.participants(name);
create index idx_teams_aliases on public.teams using gin(aliases);
create index idx_matches_date on public.matches(match_date);
create index idx_matches_status on public.matches(status);
create index idx_matches_display_order on public.matches(display_order);
create unique index idx_matches_unique_game on public.matches(match_date, team_a_id, team_b_id);
create index idx_uploads_participant_id on public.uploads(participant_id);
create index idx_uploads_status on public.uploads(status);
create index idx_import_drafts_upload_id on public.import_drafts(upload_id);
create index idx_import_rows_draft_id on public.import_draft_rows(import_draft_id);
create index idx_import_rows_status on public.import_draft_rows(status);
create index idx_predictions_participant_id on public.predictions(participant_id);
create index idx_predictions_match_id on public.predictions(match_id);
create index idx_prediction_scores_participant_id on public.prediction_scores(participant_id);
create index idx_prediction_scores_match_id on public.prediction_scores(match_id);
create index idx_ranking_snapshots_date on public.ranking_snapshots(snapshot_date);
create index idx_ranking_snapshots_participant_id on public.ranking_snapshots(participant_id);
create index idx_audit_logs_admin_user_id on public.audit_logs(admin_user_id);
create index idx_audit_logs_entity on public.audit_logs(entity_type, entity_id);
